# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be7651efb60c0fd84ea0f8339c688c82a0869c5369f176b4ccae4c611420c7a6298cb43cfc4ed2c387d935996fddf5ff8f0926884825990de6b5d0f69671c7de

test:
  secret_key_base: f7403530f4ec11e0b4ea752f21f49e48f7abf4b1fa6a0792e953e92bc946bf4ebf6854011e1b017a390ddfa60fc059122597bb82f288afd7bc5598e46fdf98dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
